image: python:latest

stages:
  - deploy

before_script:
   - pip install twine
   - python setup.py sdist

deploy_staging:
  stage: deploy
  variables:
    TWINE_USERNAME: $PYPI_USER
    TWINE_PASSWORD: $PYPI_TOKEN_TEST
  script:
    - twine upload --repository testpypi dist/*
  except:
    - tags

deploy_production:
  stage: deploy
  variables:
    TWINE_USERNAME: $PYPI_USER
    TWINE_PASSWORD: $PYPI_TOKEN_PROD
  script:
    - twine upload dist/*
  only:
    - tags