image: python:3.9

stages:
  - test
  - deploy

before_script:
   - pip install twine
   - python setup.py sdist

test_install:
  stage: test
  script:
    - apt-get update
    - apt-get install -y python3-opencv
    - apt-get install -y tesseract-ocr
    - pip install .
    - python -m unittest discover -s tests

deploy_production:
  stage: deploy
  variables:
    TWINE_USERNAME: $PYPI_USER
    TWINE_PASSWORD: $PYPI_TOKEN_PROD
  script:
    - twine upload dist/* --verbose
  only:
    - master
  when: manual
