image: python:latest

stages:
  - test
  - deploy

before_script:
   - pip install twine
   - python setup.py sdist

test_install:
  stage: test
  script:
    - python test_install.py

deploy_production:
  stage: deploy
  variables:
    TWINE_USERNAME: $PYPI_USER
    TWINE_PASSWORD: $PYPI_TOKEN_PROD
  script:
    - twine upload dist/*
  only:
    - tags
    - master